# lifter_config.yaml

ethernet_interface: "enp86s0"  # 网卡名称

# 伺服电机的上下限位
height_limits:
  min: 0  # 最小高度，单位：mm
  max: 1000  # 最大高度，单位：mm

# 伺服电机的速度限制
speed_limits:
  max: 100  # 最大速度，单位：mm/s

# 停止控制参数
stop_parameters:
  deceleration: 500  # 制动减速度，单位：mm/s^2
